name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x

      - name: Deploy to Deno Deploy
        run: |
          curl -fsSL https://deno.land/x/deploy/install.sh | sh
          deno deploy --token ${{ secrets.DENO_DEPLOY_TOKEN }} ./main.ts
